apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s7o1do1ep-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s7o1do1ep-go 
  name: s7o1do1ep-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s7o1do1ep-go 
