apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s7o1do1ep-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:13746643d86d424f9fe535c8d407258d6d965b42@sha256:0667e961c759ba992b164d40bb2f1fc5f1b7a1f9290607f8904a660bf1a4b5a1
          name: container-image
